default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aces_development
  username: aces
  host: localhost
  port: 5432

test:
  <<: *default
  database: aces_test
  username: aces
  host: localhost
  port: 5432

production:
  <<: *default
  database: aces_production
  username: aces
  password: <%= ENV['ACES_DATABASE_PASSWORD'] %>
